# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5528fc77438bbd288683ec16d69b1604b5bb38d62d7ca6755725659cd8c381fd41833f96c67477d410a4a7e458dfdc3e5cd7d4297fca430833dae872348e9bf7

test:
  secret_key_base: c9d125aa5664deb43670855720bc4864162cfbebb7320f4e143ef65aab2fa4c984b0cc159d58a07d793624532f1e96455545ccdef8feaf4063291edd36820198

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
